export function splitIntoCodeBlocks(code: string): string[] {
  const codeBlocks = code.split(/\n(?=\S)/g);

  return codeBlocks.filter((block) => block.split("\n").length >= 5);
}

export function addHeader(
  code: string,
  symbols: { open: string; close: string }
) {
  const { open, close } = symbols;

  const header = [
    open,
    `
# **************************************************************************** #
#   Comment blocks automatically generated by the Polyfact AI extension        #
#   For improved readability and precise understanding of the code.            #
#                                                                              #
#   https://polyfact.com, 2023                                                 #
#   No rights reserved.                                                        #
# **************************************************************************** #
`,
    close,
  ].join("");

  if (code.includes(header)) {
    return code;
  }

  return [header, code].join("\n\n");
}
